yunjichoi9151/Algorithm_CS_Study

LYG/Test.java
=> pull request test

LYG/0904/BOJ_1002_터렛.java, LYG/0904/BOJ_4563_리벤지오브피타고라스.java, LYG/0904/BOJ_6322_직각삼각형두변.java
=> 220904 LYG

CYJ/Baekjoon/Code/Revenge_of_Pythagoras_4563.java, CYJ/Baekjoon/Code/Turret_1002.java, CYJ/Baekjoon/Code/Two_Sides_of_Right_Triangle_6322.java, CYJ/Test.java
2022.09.04 일타싸피 대비 Baekjoon 문제 풀이 추가합니다.
6322 - 직각 삼각형의 두 변
1002 - 터렛
4563 - 리벤지 오브 피타고라스
=> Add 9.4 files

LYG/0912/BOJ_1167_트리지름.java, LYG/0912/BOJ_11725_TreeParent.java, LYG/0912/BOJ_4803_트리.java
=> 220912 LYG

HSW/0914/BOJ_2606_바이러스.java, HSW/0914/BOJ_2667_단지번호붙이기.java, HSW/0914/BOJ_7576_토마토.java
=> 20220914 HSW

LYG/0914/BOJ_2606_바이러스.java, LYG/0914/BOJ_2667_단지번호붙이기.java, LYG/0914/BOJ_7576_토마토.java
=> 220914 LYG

HSW/0918/BOJ_13460_구슬탈출2.java, HSW/0918/BOJ_5014_스타트링크.java, HSW/0918/BOJ_9205_맥주마시면서걸어가기.java
=> 20220918 HSW

CYJ/Baekjoon/Code/Escape_of_Bead_2_13460.java, CYJ/Baekjoon/Code/Matrix_Square_10830.java, CYJ/Baekjoon/Code/Star_11_2448.java, CYJ/Baekjoon/Code/StartLink_5014.java, CYJ/Baekjoon/Code/Walking_with_Beer_9205.java, CYJ/Baekjoon/Code/Z_1074.java
2022.09.18 Baekjoon 문제 풀이 추가합니다.
9205 - 맥주 마시면서 걸어가기
5014 - 스타트링크
13460 - 구슬 탈출2
=> Add 9.18 files

CYJ/Baekjoon/Code/Matrix_Square_10830.java, CYJ/Baekjoon/Code/Star_11_2448.java, CYJ/Baekjoon/Code/Z_1074.java
2022.09.21 Baekjoon 문제 풀이 추가합니다.
1074 - Z
2448 - 별 찍기 - 11
10830 - 행렬 제곱
=> Add 9.21 files(CYJ)

HSW/0921/BOJ_1074_Z.java, HSW/0921/BOJ_10830_행렬제곱.java, HSW/0921/BOJ_2448_별찍기11.java
=> 20220921 한상원

CYJ/Baekjoon/Code/Distance_of_RGB_1149.java, CYJ/Baekjoon/Code/Move_Pipe_2_17069.java, CYJ/Baekjoon/Code/Ordinary_Backpack_12865.java, CYJ/Baekjoon/Code/Running_Exciting_Functions_9184.java
2022.09.25 Baekjoon 문제 풀이 추가합니다.
9184 - 신나는 함수 실행
1149 - RGB 거리
17069 - 파이프 옮기기 2
12865 - 평범한 배낭
=> Add 9.25 files(CYJ)

CYJ/Baekjoon/Code/Cable_2565.java, CYJ/Baekjoon/Code/Climbing_Stairs_2579.java, CYJ/Baekjoon/Code/Longest_Bitonic_11054.java, CYJ/Baekjoon/Code/Longest_Increasing_Subsequence_11053.java
2022.09.28 Baekjoon 문제 풀이 추가합니다.
2579 - 계단 오르기
11053 - 가장 긴 증가하는 부분 수열
11054 - 가장 긴 바이토닉 부분 수열
2565 - 전깃줄
=> [BOJ] DP 22.09.28 CYJ

WYH/BOJ_11053.java, WYH/BOJ_1976.java, WYH/BOJ_2579.java, WYH/BOJ_9370.java
=> [BOJ] DP 22.09.28 WYH 

CYJ/Baekjoon/Code/Communion_with_Universe_God_1774.java, CYJ/Baekjoon/Code/Go_Trip_1976.java, CYJ/Baekjoon/Code/Hide_and_Seek_3_13549.java, CYJ/Baekjoon/Code/Make_Constellation_4386.java, CYJ/Baekjoon/Code/Time_Machine_11657.java, CYJ/Baekjoon/Code/Unidentified_Destination_9370.java
2022.10.05 Baekjoon 문제 풀이 추가합니다.
1774 - 우주신과의 교감
1976 - 여행 가자
4386 - 별자리 만들기
9370 - 미확인 도착지
11657 - 타임머신
13549 - 숨바꼭질 3
=> [BOJ] MST, Union-Find, Dijkstra 22.10.05 CYJ

HSW/1012/BOJ_14503_로봇청소기.java, HSW/1012/BOJ_16236_아기상어.java, HSW/1012/BOJ_이항계수3.java
=> [BOJ] Free 22.10.12 HSW

CYJ/Baekjoon/Code/Baby_Shark_16236.java, CYJ/Baekjoon/Code/Remote_Control_1107.java, CYJ/Baekjoon/Code/Robot_Cleaner_14503.java
2022.10.12 Baekjoon 문제 풀이 추가합니다.
16236 - 아기 상어
14503 - 로봇 청소기
1107 - 리모컨
=> [BOJ] Free 22.10.12 CYJ

CYJ/Programmers/Crane_Claw_Machine_Game.java, CYJ/Programmers/Open_Chat_Room.java, CYJ/Programmers/Parking_Fee_Calculation.java, CYJ/Programmers/Recommend_New_ID.java
2022.10.23 프로그래머스 문제 풀이 추가합니다.
lv1. 크레인 인형뽑기 게임
lv1. 신규 아이디 추천
lv2. 오픈채팅방
lv2. 주차 요금 계산
=> [PRGRMS] Kakao 22.10.23 CYJ

WYH/programmers1_다트게임.java, WYH/programmers2_구명보트.java, WYH/programmers3_메뉴리뉴얼.java
=> [PRGRMS] Kakao 22.10.30 WYH

CYJ/Programmers/Dart_Game.java, CYJ/Programmers/Lifeboat.java, CYJ/Programmers/Menu_Renewal.java, CYJ/Programmers/Night_Overtime_index.java
2022.10.30 프로그래머스 문제 풀이 추가합니다.
lv1. 다트 게임
lv2. 구명 보트
lv2. 메뉴 리뉴얼
lv3. 야근 지수
=> [PRGRMS] Kakao 22.10.30 CYJ

HSW/1030/PRG_구명보트.java, HSW/1030/PRG_다트게임.java, HSW/1030/PRG_메뉴리뉴얼.java, HSW/1030/PRG_야근지수.java
=>  [PRGRMS] Kakao 22.10.30 HSW

CYJ/Programmers/Collect_Stickers_2.java, CYJ/Programmers/Divide_Power_Grid_Into_Two.java, CYJ/Programmers/Friends_4_Block.java, CYJ/Programmers/Receive_Notify_Results.java
2022.11.06 프로그래머스 문제 풀이 추가합니다.
lv1. 신고 결과 받기
lv2. 프렌즈4블록
lv2. 전력망을 둘로 나누기
lv3. 스티커 모으기(2)
=> [PRGRMS] Kakao 22.11.06 CYJ

HSW/1106/PRG_스티커모으기2.java, HSW/1106/PRG_신고결과받기.java, HSW/1106/PRG_전력망둘로나누기.java, HSW/1106/PRG_프렌즈4블록.java
=>  [PRGRMS] Kakao 22.11.06 HSW

WYH/신고결과받기.java, WYH/전력망둘로나누기.java, WYH/프렌즈4블록.java
=> [PRGRMS] Kakao 22.11.06 WYH

CYJ/Programmers/Coloring_Book.java, CYJ/Programmers/Number_Game.java, CYJ/Programmers/Secret_Map.java
2022.12.04 프로그래머스 문제 풀이 추가합니다.
lv1. [1차] 비밀지도
lv2. 카카오프렌즈 컬러링북
lv3. 숫자 게임
=> [PRGRMS] Kakao 22.12.04 CYJ

HSW/1113/PRG_뉴스클러스터링.java, HSW/1113/PRG_최고의집합.java, HSW/1113/PRG_키패드누르기.java
=>  [PRGRMS] Kakao 22.11.13 HSW

HSW/230129/BOJ_17608_막대기.java, HSW/230129/기사단원의무기.js, HSW/230129/콜라문제.js
[PRGRMS] 23.01.29 HSW
자바스크립트로 풀어보는거 연습 겸 풀어본거라 알고리즘 주제 정하고 푼건 없습니다
=> [PRGRMS] 23.01.29 HSW

WYH/뉴스클러스터링.java, WYH/키패드누르기.java
=> [PRGRMS] Kakao 22.11.13 WYH

CYJ/Baekjoon/Code/달팽이는_올라가고_싶다_2869.java, CYJ/Baekjoon/Code/부녀회장이_될테야_2775.java, CYJ/Baekjoon/Code/소수_2581.java, CYJ/Baekjoon/Code/소인수분해_11653.java, CYJ/Baekjoon/Code/최댓값_2566.java
2023.02.05 Baekjoon 문제 풀이 추가합니다.
2566 - 최댓값
2581 - 소수
2775 - 부녀회장이 될테야
2869 - 달팽이는 올라가고 싶다
11653 - 소인수분해
=> [BOJ] Math 23.02.05 CYJ

CYJ/Baekjoon/Code/소수_구하기_1929.java, CYJ/Baekjoon/Code/커트라인_25305.java
2023.02.12 Baekjoon 문제 풀이 추가합니다.
1929 - 소수 구하기
25305 - 커트라인
=> [BOJ] Math 23.02.12 CYJ

CYJ/Baekjoon/Code/골드바흐의_추측_9020.java, CYJ/Baekjoon/Code/공_넣기_10810.java, CYJ/Baekjoon/Code/공_바꾸기_10813.java, CYJ/Baekjoon/Code/너의_평점은_25206.java, CYJ/Baekjoon/Code/덩치_7568.java, CYJ/Baekjoon/Code/바구니_뒤집기_10811.java, CYJ/Baekjoon/Code/베르트랑_공준_4948.java, CYJ/Baekjoon/Code/별_찍기_7_2444.java, CYJ/Baekjoon/Code/영화감독_숌_1436.java, CYJ/Baekjoon/Code/영화감독_숌_v2_1436.java, CYJ/Baekjoon/Code/제로_10773.java, CYJ/Baekjoon/Code/코딩은_체육과목입니다_25314.java, CYJ/Baekjoon/Code/통계학_2108.java
2023.02.19 Baekjoon 문제 풀이 추가합니다.
4948 - 베르트랑 공준
9020 - 골든바흐의 추측
=> [BOJ] Math 23.02.19 CYJ

CYJ/Baekjoon/Code/문자와_문자열_27866.java, CYJ/Baekjoon/Code/프린터_큐_1966.java
2023.03.12 Baekjoon 문제 풀이 추가합니다.
1966 - 프린터 큐
27866 - 문자와 문자열
=> [BOJ] Free 23.03.12 CYJ

CYJ/Baekjoon/Code/전구_21918.java, CYJ/Baekjoon/Code/최소_최대_2_20053.java
2023.03.19 Baekjoon 문제 풀이 추가합니다.
20053 - 최소, 최대 2
21918 - 전구
=> [BOJ] Implementation 23.03.19 CYJ
